RedisCassandraNapredneBazePodataka/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CassandraDataLayer;

namespace RedisCassandraNapredneBazePodataka.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Onama()
        {
            ViewBag.Message = "Your application Onama page.";

            return Content(DataProvider.GetUserByUsername("z3r0d4y").ToString());
        }

        public ActionResult GetUsers()
        {
            return Content(DataProvider.GetAllUsers()[0].ToString());
        }

        public ActionResult Delatnosti()
        {
            ViewBag.Message = "Your Delatnosti page.";

            return View();
        }
    }
}

RedisCassandraNapredneBazePodataka/Controllers/PaketController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RedisCassandraNapredneBazePodataka.Controllers
{
    public class PaketController : Controller
    {
        // GET: Paket
        public ActionResult Index()
        {
            return View();
        }
    }
}

RedisCassandraNapredneBazePodataka/Views/Home/Delatnosti.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

RedisCassandraNapredneBazePodataka/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<section class="bg-primary" id="about">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 mx-auto text-center">
                <h2 class="section-heading text-white">Najbolja nega zuba u gradu</h2>
                <hr class="light my-4">
                <p class="text-faded mb-4">Započnite svaki dan osmehom kada znate da se za Vaše zdravlje brine Dentsoft. Zajedno sa našim pouzdanim partnerima aktivno učestvujemo u preventivi većine najčešćih bolesti desni.</p>
                <a class="btn btn-light btn-xl js-scroll-trigger" href="#services">Naruči odmah</a>
            </div>
        </div>
    </div>
</section>
<section id="services">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h2 class="section-heading">At Your Service</h2>
                <hr class="my-4">
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-6 text-center">
                <div class="service-box mt-5 mx-auto">
                    <i class="fa fa-4x fa-diamond text-success mb-3 sr-icons" data-sr-id="2" style="; visibility: visible;  -webkit-transform: scale(1); opacity: 1;transform: scale(1); opacity: 1;-webkit-transition: -webkit-transform 0.6s cubic-bezier(0.6, 0.2, 0.1, 1) 0s, opacity 0.6s cubic-bezier(0.6, 0.2, 0.1, 1) 0s; transition: transform 0.6s cubic-bezier(0.6, 0.2, 0.1, 1) 0s, opacity 0.6s cubic-bezier(0.6, 0.2, 0.1, 1) 0s; "></i>
                    <h3 class="mb-3" style="text-transform:capitalize">Sturdy Templates</h3>
                    <p class="text-muted mb-0">Our templates are updated regularly so they don't break.</p>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 text-center">
                <div class="service-box mt-5 mx-auto">
                    <i class="fa fa-4x fa-paper-plane text-success mb-3 sr-icons" data-sr-id="3" style="; visibility: visible;  -webkit-transform: scale(1); opacity: 1;transform: scale(1); opacity: 1;-webkit-transition: -webkit-transform 0.6s cubic-bezier(0.6, 0.2, 0.1, 1) 0s, opacity 0.6s cubic-bezier(0.6, 0.2, 0.1, 1) 0s; transition: transform 0.6s cubic-bezier(0.6, 0.2, 0.1, 1) 0s, opacity 0.6s cubic-bezier(0.6, 0.2, 0.1, 1) 0s; "></i>
                    <h3 class="mb-3" style="text-transform:capitalize">Ready to Ship</h3>
                    <p class="text-muted mb-0">You can use this theme as is, or you can make changes!</p>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 text-center">
                <div class="service-box mt-5 mx-auto">
                    <i class="fa fa-4x fa-newspaper-o text-success mb-3 sr-icons" data-sr-id="4" style="; color:#4BBF73; visibility: visible;  -webkit-transform: scale(1); opacity: 1;transform: scale(1); opacity: 1;-webkit-transition: -webkit-transform 0.6s cubic-bezier(0.6, 0.2, 0.1, 1) 0s, opacity 0.6s cubic-bezier(0.6, 0.2, 0.1, 1) 0s; transition: transform 0.6s cubic-bezier(0.6, 0.2, 0.1, 1) 0s, opacity 0.6s cubic-bezier(0.6, 0.2, 0.1, 1) 0s; "></i>
                    <h3 class="mb-3" style="text-transform:capitalize">Up to Date</h3>
                    <p class="text-muted mb-0">We update dependencies to keep things fresh.</p>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 text-center">
                <div class="service-box mt-5 mx-auto">
                    <i class="fa fa-4x fa-heart text-success mb-3 sr-icons" data-sr-id="5" style="; visibility: visible;  -webkit-transform: scale(1); opacity: 1;transform: scale(1); opacity: 1;-webkit-transition: -webkit-transform 0.6s cubic-bezier(0.6, 0.2, 0.1, 1) 0s, opacity 0.6s cubic-bezier(0.6, 0.2, 0.1, 1) 0s; transition: transform 0.6s cubic-bezier(0.6, 0.2, 0.1, 1) 0s, opacity 0.6s cubic-bezier(0.6, 0.2, 0.1, 1) 0s; "></i>
                    <h3 class="mb-3" style="text-transform:capitalize">Made with Love</h3>
                    <p class="text-muted mb-0">You have to make your websites with love these days!</p>
                </div>
            </div>
        </div>
    </div>
</section>

RedisCassandraNapredneBazePodataka/Views/Home/Onama.cshtml
@{
    ViewBag.Title = "About";
}

<h2>Rista Rista</h2>

RedisCassandraNapredneBazePodataka/Views/Paket/Index.cshtml
@{
    Layout = "~/Views/Shared/_PaketLayout.cshtml";
}

<h1>PAKETI</h1>

<div class="container">
    <div class="card border-light mb-3" style="max-width: 20rem;">
        <div class="card-header">Header</div>
        <div class="card-body">
            <h4 class="card-title">Light card title</h4>
            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
        </div>
    </div>
</div>

RedisCassandraNapredneBazePodataka/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - DentSoft</title>
    @Styles.Render("~/Content/font-awesome/css/font-awesome.min.css")
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <a class="navbar-brand" href="#">Dentsoft</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarColor01">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    @Html.ActionLink("Početna", "Index", "Home", new { }, new { @class = "nav-link" })<span class="sr-only">(current)</span>
                </li>
                <li class="nav-item">
                    @Html.ActionLink("Paketi", "Index", "Paket", new { }, new { @class = "nav-link" })
                </li>
                <li class="nav-item">
                    @Html.ActionLink("Delatnosti", "Delatnosti", "Home", new { }, new { @class = "nav-link" })
                </li>
                <li class="nav-item">
                    @Html.ActionLink("O Nama", "Onama", "Home", new { }, new { @class = "nav-link" })
                </li>
                <li class="nav-item">
                    @Html.ActionLink("Cenovnik", "Cenovnik", "Home", new { }, new { @class = "nav-link" })
                </li>
                <li class="nav-item">
                    @Html.ActionLink("Blog", "Index", "Blog", new { }, new { @class = "nav-link" })
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Contact</a>
                </li>
            </ul>
            <ul class="navbar-nav mr-1">
                <li class="my-4 my-lg-0">
                    <a class="nav-link" href="#" style="color:#4BBF73">Prijava</a>
                </li>
                <li style="margin-top:11px">|</li>
                <li class="my-4 my-lg-0">
                    <a class="nav-link" href="#" style="color:#4BBF73">Registracija</a>
                </li>
            </ul>
        </div>
    </nav>

    <header class="jumbotron jumbotron-2 masthead text-center text-white d-flex">
        <div class="container my-auto">
                <div class="row">
                    <div class="col-lg-10 mx-auto">
                        <h1 class="display-4 text-white text-center">
                        <strong>Vaš omiljeni ortodontista sada i na webu</strong></h1>
                        <hr />
                    </div>
                    <div class="col-lg-8 mx-auto">
                        <p class="text-faded mb-5 text-white" style="text-align:center; font-size: 16px;">Proverite zašto smo najbolji u gradu. Zašto imamo toliko pozitivnih kritika, razbijajući sve predrasude o zubarima.
                        Kombinovanje dugogodišnjeg znanja sa najnovijim tehnologijama u svetu za održavanje zuba obećavamo da će Vaš osmeh blistati bolje nego ikad.</p>
                        <a class="btn btn-primary btn-xl js-scroll-trigger" href="#about">Saznajte više</a>
                    </div>
                </div>
            </div>
    </header>

    <div class="">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/Scripts/app.js")
    @RenderSection("scripts", required: false)
</body>
</html>

RedisCassandraNapredneBazePodataka/Views/Shared/_PaketLayout.cshtml
@{ 
    ViewBag.Title = "DentSoft";
}

<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewBag.Title - Paketi</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <a class="navbar-brand" href="#">Dentsoft</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarColor01">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    @Html.ActionLink("Početna", "Index", "Home", new { }, new { @class = "nav-link" })<span class="sr-only">(current)</span>
                </li>
                <li class="nav-item">
                    @Html.ActionLink("Paketi", "Index", "Paket", new { }, new { @class = "nav-link" })
                </li>
                <li class="nav-item">
                    @Html.ActionLink("Delatnosti", "Delatnosti", "Home", new { }, new { @class = "nav-link" })
                </li>
                <li class="nav-item">
                    @Html.ActionLink("O Nama", "Onama", "Home", new { }, new { @class = "nav-link" })
                </li>
                <li class="nav-item">
                    @Html.ActionLink("Cenovnik", "Cenovnik", "Home", new { }, new { @class = "nav-link" })
                </li>
                <li class="nav-item">
                    @Html.ActionLink("Blog", "Index", "Blog", new { }, new { @class = "nav-link" })
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Contact</a>
                </li>
            </ul>
            <ul class="navbar-nav mr-1">
                <li class="my-4 my-lg-0">
                    <a class="nav-link" href="#" style="color:#4BBF73">Prijava</a>
                </li>
                <li style="margin-top:11px">|</li>
                <li class="my-4 my-lg-0">
                    <a class="nav-link" href="#" style="color:#4BBF73">Registracija</a>
                </li>
            </ul>
        </div>
    </nav> <!-- NAVIGACIJA END-->

    <div>
        @RenderBody()
    </div>

    <footer>
        <div class="container">
            <p class="text-white">&copy; DateTime.Year - DentSoft</p>
        </div>
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/Scripts/app.js")
    @RenderSection("scripts", required: false);
</body>
</html>